/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DIDApiService is a service that implements the logic for the DIDApiServicer
// This service should implement the business logic for every endpoint for the DIDApi API.
// Include any external packages or services that will be required by this service.
type DIDApiService struct {
}

// NewDIDApiService creates a default api service
func NewDIDApiService() DIDApiServicer {
	return &DIDApiService{}
}

// DIDGetPublic - Get public DID
func (s *DIDApiService) DIDGetPublic(ctx context.Context) (ImplResponse, error) {
	// TODO - update DIDGetPublic with the required logic for this service method.
	// Add api_did_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, DidGetPublic200Response{}) or use other options such as http.Ok ...
	//return Response(200, DidGetPublic200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DIDGetPublic method not implemented")
}
