/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"

	"github.com/findy-network/findy-agent-backchannel/agent"
)

// DIDApiService is a service that implents the logic for the DIDApiServicer
// This service should implement the business logic for every endpoint for the DIDApi API.
// Include any external packages or services that will be required by this service.
type DIDApiService struct {
	a *agent.Agent
}

// NewDIDApiService creates a default api service
func NewDIDApiService(a *agent.Agent) DIDApiServicer {
	return &DIDApiService{
		a: a,
	}
}

// DIDGetPublic - Get public DID
func (s *DIDApiService) DIDGetPublic(ctx context.Context) (ImplResponse, error) {
	return Response(200, InlineResponse2003{
		Did:    "Y9oNbFNTgxrRuvxQk3xEzr",                       // TODO
		Verkey: "HymVhRozF7o9Sh9iyKXu5WKHP95YERhrpZxGx5d6WhYw", // TODO
	}), nil
}
