/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// IssueCredentialApiService is a service that implements the logic for the IssueCredentialApiServicer
// This service should implement the business logic for every endpoint for the IssueCredentialApi API.
// Include any external packages or services that will be required by this service.
type IssueCredentialApiService struct {
}

// NewIssueCredentialApiService creates a default api service
func NewIssueCredentialApiService() IssueCredentialApiServicer {
	return &IssueCredentialApiService{}
}

// IssueCredentialCreateOffer - Create credential offer.
func (s *IssueCredentialApiService) IssueCredentialCreateOffer(ctx context.Context, issueCredentialCreateOfferRequest IssueCredentialCreateOfferRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialCreateOffer with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialCreateOffer200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialCreateOffer200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialCreateOffer method not implemented")
}

// IssueCredentialGetByThreadId - Get credential exchange record by thread id
func (s *IssueCredentialApiService) IssueCredentialGetByThreadId(ctx context.Context, credentialExchangeThreadId string) (ImplResponse, error) {
	// TODO - update IssueCredentialGetByThreadId with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialOperationResponse{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialOperationResponse{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialGetByThreadId method not implemented")
}

// IssueCredentialIssue - Issue Credential
func (s *IssueCredentialApiService) IssueCredentialIssue(ctx context.Context, issueCredentialIssueRequest IssueCredentialIssueRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialIssue with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialIssue200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialIssue200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialIssue method not implemented")
}

// IssueCredentialSendOffer - Send credential offer
func (s *IssueCredentialApiService) IssueCredentialSendOffer(ctx context.Context, issueCredentialSendOfferRequest IssueCredentialSendOfferRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialSendOffer with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialCreateOffer200ResponseRecord{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialCreateOffer200ResponseRecord{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialSendOffer method not implemented")
}

// IssueCredentialSendProposal - Send credential proposal
func (s *IssueCredentialApiService) IssueCredentialSendProposal(ctx context.Context, issueCredentialSendProposalRequest IssueCredentialSendProposalRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialSendProposal with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialSendProposal200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialSendProposal200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialSendProposal method not implemented")
}

// IssueCredentialSendRequest - Send credential request
func (s *IssueCredentialApiService) IssueCredentialSendRequest(ctx context.Context, issueCredentialSendRequestRequest IssueCredentialSendRequestRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialSendRequest with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialSendRequest200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialSendRequest200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialSendRequest method not implemented")
}

// IssueCredentialStore - Store Credential
func (s *IssueCredentialApiService) IssueCredentialStore(ctx context.Context, issueCredentialStoreRequest IssueCredentialStoreRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialStore with the required logic for this service method.
	// Add api_issue_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialStore200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialStore200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialStore method not implemented")
}
