/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// DIDApiController binds http requests to an api service and writes the service results to the http response
type DIDApiController struct {
	service      DIDApiServicer
	errorHandler ErrorHandler
}

// DIDApiOption for how the controller is set up.
type DIDApiOption func(*DIDApiController)

// WithDIDApiErrorHandler inject ErrorHandler into controller
func WithDIDApiErrorHandler(h ErrorHandler) DIDApiOption {
	return func(c *DIDApiController) {
		c.errorHandler = h
	}
}

// NewDIDApiController creates a default api controller
func NewDIDApiController(s DIDApiServicer, opts ...DIDApiOption) Router {
	controller := &DIDApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DIDApiController
func (c *DIDApiController) Routes() Routes {
	return Routes{
		{
			"DIDGetPublic",
			strings.ToUpper("Get"),
			"/agent/command/did",
			c.DIDGetPublic,
		},
	}
}

// DIDGetPublic - Get public DID
func (c *DIDApiController) DIDGetPublic(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.DIDGetPublic(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
