/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"log"
	"net/http"

	"github.com/findy-network/findy-agent-backchannel/agent"
)

// CredentialApiService is a service that implements the logic for the CredentialApiServicer
// This service should implement the business logic for every endpoint for the CredentialApi API.
// Include any external packages or services that will be required by this service.
type CredentialApiService struct {
	a *agent.Agent
}

// NewCredentialApiService creates a default api service
func NewCredentialApiService(a *agent.Agent) CredentialApiServicer {
	return &CredentialApiService{a: a}
}

// CredentialDeleteById - Delete credential by id
func (s *CredentialApiService) CredentialDeleteById(ctx context.Context, credentialId string) (ImplResponse, error) {
	// TODO - update CredentialDeleteById with the required logic for this service method.
	// Add api_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CredentialDeleteById method not implemented")
}

// CredentialGetById - Get credential by id
func (s *CredentialApiService) CredentialGetById(ctx context.Context, credentialId string) (ImplResponse, error) {
	cred, err := s.a.GetCredentialContent(credentialId)
	log.Println("Credential content", cred, credentialId)
	if err != nil {
		return Response(http.StatusNotFound, nil), err
	}
	return Response(200, cred), nil
}

// CredentialGetRevocationStatusById - Get Credential Revocation Status
func (s *CredentialApiService) CredentialGetRevocationStatusById(ctx context.Context, credentialId string) (ImplResponse, error) {
	// TODO - update CredentialGetRevocationStatusById with the required logic for this service method.
	// Add api_credential_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CredentialGetRevocationStatusById200Response{}) or use other options such as http.Ok ...
	//return Response(200, CredentialGetRevocationStatusById200Response{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CredentialGetRevocationStatusById method not implemented")
}
