/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// OutOfBandApiService is a service that implements the logic for the OutOfBandApiServicer
// This service should implement the business logic for every endpoint for the OutOfBandApi API.
// Include any external packages or services that will be required by this service.
type OutOfBandApiService struct {
}

// NewOutOfBandApiService creates a default api service
func NewOutOfBandApiService() OutOfBandApiServicer {
	return &OutOfBandApiService{}
}

// OutOfBandCreateInvitation - Create a new out of band invitation
func (s *OutOfBandApiService) OutOfBandCreateInvitation(ctx context.Context, outOfBandCreateInvitationRequest OutOfBandCreateInvitationRequest) (ImplResponse, error) {
	// TODO - update OutOfBandCreateInvitation with the required logic for this service method.
	// Add api_out_of_band_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, OutOfBandCreateInvitation200Response{}) or use other options such as http.Ok ...
	//return Response(200, OutOfBandCreateInvitation200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OutOfBandCreateInvitation method not implemented")
}

// OutOfBandReceiveInvitation - Receive an out of band invitation
func (s *OutOfBandApiService) OutOfBandReceiveInvitation(ctx context.Context, outOfBandReceiveInvitationRequest OutOfBandReceiveInvitationRequest) (ImplResponse, error) {
	// TODO - update OutOfBandReceiveInvitation with the required logic for this service method.
	// Add api_out_of_band_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, OutOfBandReceiveInvitation200Response{}) or use other options such as http.Ok ...
	//return Response(200, OutOfBandReceiveInvitation200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OutOfBandReceiveInvitation method not implemented")
}
