/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// IssueCredentialV3ApiService is a service that implements the logic for the IssueCredentialV3ApiServicer
// This service should implement the business logic for every endpoint for the IssueCredentialV3Api API.
// Include any external packages or services that will be required by this service.
type IssueCredentialV3ApiService struct {
}

// NewIssueCredentialV3ApiService creates a default api service
func NewIssueCredentialV3ApiService() IssueCredentialV3ApiServicer {
	return &IssueCredentialV3ApiService{}
}

// IssueCredentialV3Issue - Issue credential
func (s *IssueCredentialV3ApiService) IssueCredentialV3Issue(ctx context.Context, issueCredentialV3IssueRequest IssueCredentialV3IssueRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialV3Issue with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialIssue200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialIssue200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3Issue method not implemented")
}

// IssueCredentialV3RetrieveCredentialApplication - Retrieves the Credential Application object received by the agent.
func (s *IssueCredentialV3ApiService) IssueCredentialV3RetrieveCredentialApplication(ctx context.Context) (ImplResponse, error) {
	// TODO - update IssueCredentialV3RetrieveCredentialApplication with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3RetrieveCredentialApplication method not implemented")
}

// IssueCredentialV3RetrieveCredentialProposal - Retrieves the Propose Credential object received by the agent.
func (s *IssueCredentialV3ApiService) IssueCredentialV3RetrieveCredentialProposal(ctx context.Context) (ImplResponse, error) {
	// TODO - update IssueCredentialV3RetrieveCredentialProposal with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3RetrieveCredentialProposal method not implemented")
}

// IssueCredentialV3SendOffer - Send credential offer
func (s *IssueCredentialV3ApiService) IssueCredentialV3SendOffer(ctx context.Context, body map[string]interface{}) (ImplResponse, error) {
	// TODO - update IssueCredentialV3SendOffer with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialCreateOffer200ResponseRecord{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialCreateOffer200ResponseRecord{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3SendOffer method not implemented")
}

// IssueCredentialV3SendProposal - Send credential proposal
func (s *IssueCredentialV3ApiService) IssueCredentialV3SendProposal(ctx context.Context, issueCredentialV3SendProposalRequest IssueCredentialV3SendProposalRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialV3SendProposal with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialSendProposal200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialSendProposal200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3SendProposal method not implemented")
}

// IssueCredentialV3SendRequest - Send credential request
func (s *IssueCredentialV3ApiService) IssueCredentialV3SendRequest(ctx context.Context, body map[string]interface{}) (ImplResponse, error) {
	// TODO - update IssueCredentialV3SendRequest with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialSendRequest200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialSendRequest200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3SendRequest method not implemented")
}

// IssueCredentialV3Store - Store/accept credential
func (s *IssueCredentialV3ApiService) IssueCredentialV3Store(ctx context.Context, issueCredentialStoreRequest IssueCredentialStoreRequest) (ImplResponse, error) {
	// TODO - update IssueCredentialV3Store with the required logic for this service method.
	// Add api_issue_credential_v3_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, IssueCredentialStore200Response{}) or use other options such as http.Ok ...
	//return Response(200, IssueCredentialStore200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IssueCredentialV3Store method not implemented")
}
