/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"
)

// A StatusApiController binds http requests to an api service and writes the service results to the http response
type StatusApiController struct {
	service StatusApiServicer
}

// NewStatusApiController creates a default api controller
func NewStatusApiController(s StatusApiServicer) Router {
	return &StatusApiController{service: s}
}

// Routes returns all of the api route for the StatusApiController
func (c *StatusApiController) Routes() Routes {
	return Routes{
		{
			"StatusGet",
			strings.ToUpper("Get"),
			"/agent/command/{status:status\\/?}",
			c.StatusGet,
		},
		{
			"StatusGet_0",
			strings.ToUpper("Get"),
			"/agent/command/version",
			c.StatusGet_1,
		},
	}
}

// StatusGet - Get agent/backchannel status
func (c *StatusApiController) StatusGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.StatusGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// StatusGet_1 - Get agent/backchannel version
func (c *StatusApiController) StatusGet_1(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.StatusGet(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
