/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AgentApiService is a service that implements the logic for the AgentApiServicer
// This service should implement the business logic for every endpoint for the AgentApi API.
// Include any external packages or services that will be required by this service.
type AgentApiService struct {
}

// NewAgentApiService creates a default api service
func NewAgentApiService() AgentApiServicer {
	return &AgentApiService{}
}

// AgentStart - (re)start the agent
func (s *AgentApiService) AgentStart(ctx context.Context, agentStartRequest AgentStartRequest) (ImplResponse, error) {
	// TODO - update AgentStart with the required logic for this service method.
	// Add api_agent_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	//return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AgentStart method not implemented")
}
