/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CredentialDefinitionApiService is a service that implements the logic for the CredentialDefinitionApiServicer
// This service should implement the business logic for every endpoint for the CredentialDefinitionApi API.
// Include any external packages or services that will be required by this service.
type CredentialDefinitionApiService struct {
}

// NewCredentialDefinitionApiService creates a default api service
func NewCredentialDefinitionApiService() CredentialDefinitionApiServicer {
	return &CredentialDefinitionApiService{}
}

// CredentialDefinitionCreate - Create a new credential definition
func (s *CredentialDefinitionApiService) CredentialDefinitionCreate(ctx context.Context, credentialDefinitionCreateRequest CredentialDefinitionCreateRequest) (ImplResponse, error) {
	// TODO - update CredentialDefinitionCreate with the required logic for this service method.
	// Add api_credential_definition_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CredentialDefinitionCreate200Response{}) or use other options such as http.Ok ...
	//return Response(200, CredentialDefinitionCreate200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CredentialDefinitionCreate method not implemented")
}

// CredentialDefinitionGetById - Get credential definition by id
func (s *CredentialDefinitionApiService) CredentialDefinitionGetById(ctx context.Context, credentialDefinitionId string) (ImplResponse, error) {
	// TODO - update CredentialDefinitionGetById with the required logic for this service method.
	// Add api_credential_definition_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CredentialDefinitionGetById method not implemented")
}
