/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendProposal struct {

	Data SendProposalData `json:"data"`
}

// AssertSendProposalRequired checks if the required fields are not zero-ed
func AssertSendProposalRequired(obj SendProposal) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendProposalDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSendProposalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendProposal (e.g. [][]SendProposal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendProposalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendProposal, ok := obj.(SendProposal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendProposalRequired(aSendProposal)
	})
}
