/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AgentStartRequestDataParameters struct {

	MimeType string `json:"mime-type,omitempty"`

	InboundTransports []string `json:"inbound_transports,omitempty"`

	OutboundTransports []string `json:"outbound_transports,omitempty"`
}

// AssertAgentStartRequestDataParametersRequired checks if the required fields are not zero-ed
func AssertAgentStartRequestDataParametersRequired(obj AgentStartRequestDataParameters) error {
	return nil
}

// AssertRecurseAgentStartRequestDataParametersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AgentStartRequestDataParameters (e.g. [][]AgentStartRequestDataParameters), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAgentStartRequestDataParametersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAgentStartRequestDataParameters, ok := obj.(AgentStartRequestDataParameters)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAgentStartRequestDataParametersRequired(aAgentStartRequestDataParameters)
	})
}
