/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AgentStartRequestData struct {

	Parameters AgentStartRequestDataParameters `json:"parameters"`
}

// AssertAgentStartRequestDataRequired checks if the required fields are not zero-ed
func AssertAgentStartRequestDataRequired(obj AgentStartRequestData) error {
	elements := map[string]interface{}{
		"parameters": obj.Parameters,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAgentStartRequestDataParametersRequired(obj.Parameters); err != nil {
		return err
	}
	return nil
}

// AssertRecurseAgentStartRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AgentStartRequestData (e.g. [][]AgentStartRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAgentStartRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAgentStartRequestData, ok := obj.(AgentStartRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAgentStartRequestDataRequired(aAgentStartRequestData)
	})
}
