/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SendRequestInResponseToOffer1 - It is currently not possible yet to start from a credential request, even though supported for some credential types (e.g. JSON-LD)
type SendRequestInResponseToOffer1 struct {

	Id string `json:"id"`
}

// AssertSendRequestInResponseToOffer1Required checks if the required fields are not zero-ed
func AssertSendRequestInResponseToOffer1Required(obj SendRequestInResponseToOffer1) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSendRequestInResponseToOffer1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendRequestInResponseToOffer1 (e.g. [][]SendRequestInResponseToOffer1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendRequestInResponseToOffer1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendRequestInResponseToOffer1, ok := obj.(SendRequestInResponseToOffer1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendRequestInResponseToOffer1Required(aSendRequestInResponseToOffer1)
	})
}
