/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofV2VerifyPresentation200Response struct {

	State *interface{} `json:"state"`

	ThreadId string `json:"thread_id"`

	Verified bool `json:"verified"`
}

// AssertPresentProofV2VerifyPresentation200ResponseRequired checks if the required fields are not zero-ed
func AssertPresentProofV2VerifyPresentation200ResponseRequired(obj PresentProofV2VerifyPresentation200Response) error {
	elements := map[string]interface{}{
		"state": obj.State,
		"thread_id": obj.ThreadId,
		"verified": obj.Verified,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentProofV2VerifyPresentation200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofV2VerifyPresentation200Response (e.g. [][]PresentProofV2VerifyPresentation200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofV2VerifyPresentation200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofV2VerifyPresentation200Response, ok := obj.(PresentProofV2VerifyPresentation200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofV2VerifyPresentation200ResponseRequired(aPresentProofV2VerifyPresentation200Response)
	})
}
