/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionReceiveInvitationRequest struct {

	Data ConnectionReceiveInvitationRequestData `json:"data"`
}

// AssertConnectionReceiveInvitationRequestRequired checks if the required fields are not zero-ed
func AssertConnectionReceiveInvitationRequestRequired(obj ConnectionReceiveInvitationRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertConnectionReceiveInvitationRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseConnectionReceiveInvitationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionReceiveInvitationRequest (e.g. [][]ConnectionReceiveInvitationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionReceiveInvitationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionReceiveInvitationRequest, ok := obj.(ConnectionReceiveInvitationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionReceiveInvitationRequestRequired(aConnectionReceiveInvitationRequest)
	})
}
