/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofSendPresentationRequest struct {

	Id string `json:"id"`

	Data PresentProofSendPresentationRequestData `json:"data"`
}

// AssertPresentProofSendPresentationRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofSendPresentationRequestRequired(obj PresentProofSendPresentationRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPresentProofSendPresentationRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecursePresentProofSendPresentationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofSendPresentationRequest (e.g. [][]PresentProofSendPresentationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofSendPresentationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofSendPresentationRequest, ok := obj.(PresentProofSendPresentationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofSendPresentationRequestRequired(aPresentProofSendPresentationRequest)
	})
}
