/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OutOfBandReceiveInvitation200Response struct {

	ConnectionId string `json:"connection_id"`

	State DidExchangeState `json:"state"`
}

// AssertOutOfBandReceiveInvitation200ResponseRequired checks if the required fields are not zero-ed
func AssertOutOfBandReceiveInvitation200ResponseRequired(obj OutOfBandReceiveInvitation200Response) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"state": obj.State,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDidExchangeStateRequired(obj.State); err != nil {
		return err
	}
	return nil
}

// AssertRecurseOutOfBandReceiveInvitation200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OutOfBandReceiveInvitation200Response (e.g. [][]OutOfBandReceiveInvitation200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOutOfBandReceiveInvitation200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOutOfBandReceiveInvitation200Response, ok := obj.(OutOfBandReceiveInvitation200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOutOfBandReceiveInvitation200ResponseRequired(aOutOfBandReceiveInvitation200Response)
	})
}
