/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionCreateInvitation200Response struct {

	ConnectionId string `json:"connection_id"`

	Invitation map[string]interface{} `json:"invitation"`
}

// AssertConnectionCreateInvitation200ResponseRequired checks if the required fields are not zero-ed
func AssertConnectionCreateInvitation200ResponseRequired(obj ConnectionCreateInvitation200Response) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"invitation": obj.Invitation,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseConnectionCreateInvitation200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionCreateInvitation200Response (e.g. [][]ConnectionCreateInvitation200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionCreateInvitation200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionCreateInvitation200Response, ok := obj.(ConnectionCreateInvitation200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionCreateInvitation200ResponseRequired(aConnectionCreateInvitation200Response)
	})
}
