/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendOfferInResponseToProposal struct {

	Id string `json:"id"`
}

// AssertSendOfferInResponseToProposalRequired checks if the required fields are not zero-ed
func AssertSendOfferInResponseToProposalRequired(obj SendOfferInResponseToProposal) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSendOfferInResponseToProposalRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendOfferInResponseToProposal (e.g. [][]SendOfferInResponseToProposal), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendOfferInResponseToProposalRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendOfferInResponseToProposal, ok := obj.(SendOfferInResponseToProposal)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendOfferInResponseToProposalRequired(aSendOfferInResponseToProposal)
	})
}
