/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OutOfBandCreateInvitationRequestData struct {

	MediatorConnectionId string `json:"mediator_connection_id,omitempty"`

	UsePublicDid bool `json:"use_public_did,omitempty"`

	Attachments []map[string]interface{} `json:"attachments,omitempty"`

	HandshakeProtocols []string `json:"handshake_protocols,omitempty"`
}

// AssertOutOfBandCreateInvitationRequestDataRequired checks if the required fields are not zero-ed
func AssertOutOfBandCreateInvitationRequestDataRequired(obj OutOfBandCreateInvitationRequestData) error {
	return nil
}

// AssertRecurseOutOfBandCreateInvitationRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OutOfBandCreateInvitationRequestData (e.g. [][]OutOfBandCreateInvitationRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOutOfBandCreateInvitationRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOutOfBandCreateInvitationRequestData, ok := obj.(OutOfBandCreateInvitationRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOutOfBandCreateInvitationRequestDataRequired(aOutOfBandCreateInvitationRequestData)
	})
}
