/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DidGetPublic200Response struct {

	Did string `json:"did,omitempty"`

	Verkey string `json:"verkey,omitempty"`
}

// AssertDidGetPublic200ResponseRequired checks if the required fields are not zero-ed
func AssertDidGetPublic200ResponseRequired(obj DidGetPublic200Response) error {
	return nil
}

// AssertRecurseDidGetPublic200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DidGetPublic200Response (e.g. [][]DidGetPublic200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDidGetPublic200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDidGetPublic200Response, ok := obj.(DidGetPublic200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDidGetPublic200ResponseRequired(aDidGetPublic200Response)
	})
}
