/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendOfferToStartCredentialIssuanceFlow struct {

	Data SendOfferToStartCredentialIssuanceFlowData `json:"data"`
}

// AssertSendOfferToStartCredentialIssuanceFlowRequired checks if the required fields are not zero-ed
func AssertSendOfferToStartCredentialIssuanceFlowRequired(obj SendOfferToStartCredentialIssuanceFlow) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendOfferToStartCredentialIssuanceFlowDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSendOfferToStartCredentialIssuanceFlowRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendOfferToStartCredentialIssuanceFlow (e.g. [][]SendOfferToStartCredentialIssuanceFlow), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendOfferToStartCredentialIssuanceFlowRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendOfferToStartCredentialIssuanceFlow, ok := obj.(SendOfferToStartCredentialIssuanceFlow)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendOfferToStartCredentialIssuanceFlowRequired(aSendOfferToStartCredentialIssuanceFlow)
	})
}
