/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2SendProposalRequestData struct {

	ConnectionId string `json:"connection_id"`

	CredentialPreview IssueCredentialV2SendProposalRequestDataCredentialPreview `json:"credential_preview,omitempty"`

	Filter IssueCredentialV2CredentialProposalFilter `json:"filter"`
}

// AssertIssueCredentialV2SendProposalRequestDataRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2SendProposalRequestDataRequired(obj IssueCredentialV2SendProposalRequestData) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"filter": obj.Filter,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialV2SendProposalRequestDataCredentialPreviewRequired(obj.CredentialPreview); err != nil {
		return err
	}
	if err := AssertIssueCredentialV2CredentialProposalFilterRequired(obj.Filter); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialV2SendProposalRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2SendProposalRequestData (e.g. [][]IssueCredentialV2SendProposalRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2SendProposalRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2SendProposalRequestData, ok := obj.(IssueCredentialV2SendProposalRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2SendProposalRequestDataRequired(aIssueCredentialV2SendProposalRequestData)
	})
}
