/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AgentCommandCredentialDefinitionData struct {

	SupportRevocation bool `json:"support_revocation"`

	SchemaId string `json:"schema_id"`

	Tag string `json:"tag"`
}
