/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionAcceptInvitationRequest struct {

	Id string `json:"id"`
}

// AssertConnectionAcceptInvitationRequestRequired checks if the required fields are not zero-ed
func AssertConnectionAcceptInvitationRequestRequired(obj ConnectionAcceptInvitationRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseConnectionAcceptInvitationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionAcceptInvitationRequest (e.g. [][]ConnectionAcceptInvitationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionAcceptInvitationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionAcceptInvitationRequest, ok := obj.(ConnectionAcceptInvitationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionAcceptInvitationRequestRequired(aConnectionAcceptInvitationRequest)
	})
}
