/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialCreateOffer200Response struct {

	Message map[string]interface{} `json:"message,omitempty"`

	Record IssueCredentialCreateOffer200ResponseRecord `json:"record,omitempty"`
}

// AssertIssueCredentialCreateOffer200ResponseRequired checks if the required fields are not zero-ed
func AssertIssueCredentialCreateOffer200ResponseRequired(obj IssueCredentialCreateOffer200Response) error {
	if err := AssertIssueCredentialCreateOffer200ResponseRecordRequired(obj.Record); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialCreateOffer200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialCreateOffer200Response (e.g. [][]IssueCredentialCreateOffer200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialCreateOffer200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialCreateOffer200Response, ok := obj.(IssueCredentialCreateOffer200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialCreateOffer200ResponseRequired(aIssueCredentialCreateOffer200Response)
	})
}
