/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentationPreviewPredicatesInner struct {

	Name string `json:"name"`

	CredDefId string `json:"cred_def_id"`

	Predicate string `json:"predicate"`

	Threshold string `json:"threshold"`
}

// AssertPresentationPreviewPredicatesInnerRequired checks if the required fields are not zero-ed
func AssertPresentationPreviewPredicatesInnerRequired(obj PresentationPreviewPredicatesInner) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"cred_def_id": obj.CredDefId,
		"predicate": obj.Predicate,
		"threshold": obj.Threshold,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentationPreviewPredicatesInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentationPreviewPredicatesInner (e.g. [][]PresentationPreviewPredicatesInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentationPreviewPredicatesInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentationPreviewPredicatesInner, ok := obj.(PresentationPreviewPredicatesInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentationPreviewPredicatesInnerRequired(aPresentationPreviewPredicatesInner)
	})
}
