/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofVerifyPresentationRequest struct {

	Id string `json:"id"`
}

// AssertPresentProofVerifyPresentationRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofVerifyPresentationRequestRequired(obj PresentProofVerifyPresentationRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentProofVerifyPresentationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofVerifyPresentationRequest (e.g. [][]PresentProofVerifyPresentationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofVerifyPresentationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofVerifyPresentationRequest, ok := obj.(PresentProofVerifyPresentationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofVerifyPresentationRequestRequired(aPresentProofVerifyPresentationRequest)
	})
}
