/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateOfferToStartCredentialIssuanceFlow1Data struct {

	CredentialPreview IssueCredentialV2SendProposalRequestDataCredentialPreview `json:"credential_preview,omitempty"`

	Filter IssueCredentialV2CredentialProposalFilter `json:"filter"`
}

// AssertCreateOfferToStartCredentialIssuanceFlow1DataRequired checks if the required fields are not zero-ed
func AssertCreateOfferToStartCredentialIssuanceFlow1DataRequired(obj CreateOfferToStartCredentialIssuanceFlow1Data) error {
	elements := map[string]interface{}{
		"filter": obj.Filter,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialV2SendProposalRequestDataCredentialPreviewRequired(obj.CredentialPreview); err != nil {
		return err
	}
	if err := AssertIssueCredentialV2CredentialProposalFilterRequired(obj.Filter); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateOfferToStartCredentialIssuanceFlow1DataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateOfferToStartCredentialIssuanceFlow1Data (e.g. [][]CreateOfferToStartCredentialIssuanceFlow1Data), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateOfferToStartCredentialIssuanceFlow1DataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateOfferToStartCredentialIssuanceFlow1Data, ok := obj.(CreateOfferToStartCredentialIssuanceFlow1Data)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateOfferToStartCredentialIssuanceFlow1DataRequired(aCreateOfferToStartCredentialIssuanceFlow1Data)
	})
}
