/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendDifProofRequestData struct {

	ConnectionId string `json:"connection_id"`

	PresentationRequest SendDifProofRequestDataPresentationRequest `json:"presentation_request"`
}

// AssertSendDifProofRequestDataRequired checks if the required fields are not zero-ed
func AssertSendDifProofRequestDataRequired(obj SendDifProofRequestData) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"presentation_request": obj.PresentationRequest,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendDifProofRequestDataPresentationRequestRequired(obj.PresentationRequest); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSendDifProofRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendDifProofRequestData (e.g. [][]SendDifProofRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendDifProofRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendDifProofRequestData, ok := obj.(SendDifProofRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendDifProofRequestDataRequired(aSendDifProofRequestData)
	})
}
