/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf struct {

	Type *interface{} `json:"@type,omitempty"`
}

// AssertIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOfRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOfRequired(obj IssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf) error {
	return nil
}

// AssertRecurseIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf (e.g. [][]IssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf, ok := obj.(IssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOfRequired(aIssueCredentialV2SendProposalRequestDataCredentialPreviewAllOf)
	})
}
