/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionAcceptInvitation200Response struct {

	ConnectionId string `json:"connection_id,omitempty"`

	State ConnectionState `json:"state,omitempty"`
}

// AssertConnectionAcceptInvitation200ResponseRequired checks if the required fields are not zero-ed
func AssertConnectionAcceptInvitation200ResponseRequired(obj ConnectionAcceptInvitation200Response) error {
	if err := AssertConnectionStateRequired(obj.State); err != nil {
		return err
	}
	return nil
}

// AssertRecurseConnectionAcceptInvitation200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionAcceptInvitation200Response (e.g. [][]ConnectionAcceptInvitation200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionAcceptInvitation200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionAcceptInvitation200Response, ok := obj.(ConnectionAcceptInvitation200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionAcceptInvitation200ResponseRequired(aConnectionAcceptInvitation200Response)
	})
}
