/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofSendRequestRequest struct {

	Data PresentProofSendRequestRequestData `json:"data"`
}

// AssertPresentProofSendRequestRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofSendRequestRequestRequired(obj PresentProofSendRequestRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPresentProofSendRequestRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecursePresentProofSendRequestRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofSendRequestRequest (e.g. [][]PresentProofSendRequestRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofSendRequestRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofSendRequestRequest, ok := obj.(PresentProofSendRequestRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofSendRequestRequestRequired(aPresentProofSendRequestRequest)
	})
}
