/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendDifProofRequest struct {

	Data SendDifProofRequestData `json:"data"`
}

// AssertSendDifProofRequestRequired checks if the required fields are not zero-ed
func AssertSendDifProofRequestRequired(obj SendDifProofRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendDifProofRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSendDifProofRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendDifProofRequest (e.g. [][]SendDifProofRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendDifProofRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendDifProofRequest, ok := obj.(SendDifProofRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendDifProofRequestRequired(aSendDifProofRequest)
	})
}
