/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2CreateOffer200Response struct {

	Message map[string]interface{} `json:"message,omitempty"`

	Record IssueCredentialCreateOffer200ResponseRecord `json:"record,omitempty"`
}

// AssertIssueCredentialV2CreateOffer200ResponseRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2CreateOffer200ResponseRequired(obj IssueCredentialV2CreateOffer200Response) error {
	if err := AssertIssueCredentialCreateOffer200ResponseRecordRequired(obj.Record); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialV2CreateOffer200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2CreateOffer200Response (e.g. [][]IssueCredentialV2CreateOffer200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2CreateOffer200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2CreateOffer200Response, ok := obj.(IssueCredentialV2CreateOffer200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2CreateOffer200ResponseRequired(aIssueCredentialV2CreateOffer200Response)
	})
}
