/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV3IssueRequest struct {

	Id string `json:"id"`

	Data map[string]interface{} `json:"data,omitempty"`
}

// AssertIssueCredentialV3IssueRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV3IssueRequestRequired(obj IssueCredentialV3IssueRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIssueCredentialV3IssueRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV3IssueRequest (e.g. [][]IssueCredentialV3IssueRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV3IssueRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV3IssueRequest, ok := obj.(IssueCredentialV3IssueRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV3IssueRequestRequired(aIssueCredentialV3IssueRequest)
	})
}
