/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StatusGet418Response struct {

	Status string `json:"status"`
}

// AssertStatusGet418ResponseRequired checks if the required fields are not zero-ed
func AssertStatusGet418ResponseRequired(obj StatusGet418Response) error {
	elements := map[string]interface{}{
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseStatusGet418ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StatusGet418Response (e.g. [][]StatusGet418Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStatusGet418ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStatusGet418Response, ok := obj.(StatusGet418Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStatusGet418ResponseRequired(aStatusGet418Response)
	})
}
