/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CoordinateMediationOperationResponse struct {

	ConnectionId string `json:"connection_id"`

	State CoordinateMediationState `json:"state"`
}

// AssertCoordinateMediationOperationResponseRequired checks if the required fields are not zero-ed
func AssertCoordinateMediationOperationResponseRequired(obj CoordinateMediationOperationResponse) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"state": obj.State,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCoordinateMediationOperationResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CoordinateMediationOperationResponse (e.g. [][]CoordinateMediationOperationResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCoordinateMediationOperationResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCoordinateMediationOperationResponse, ok := obj.(CoordinateMediationOperationResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCoordinateMediationOperationResponseRequired(aCoordinateMediationOperationResponse)
	})
}
