/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2SendRequestRequest struct {

	Id string `json:"id"`
}

// AssertIssueCredentialV2SendRequestRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2SendRequestRequestRequired(obj IssueCredentialV2SendRequestRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIssueCredentialV2SendRequestRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2SendRequestRequest (e.g. [][]IssueCredentialV2SendRequestRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2SendRequestRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2SendRequestRequest, ok := obj.(IssueCredentialV2SendRequestRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2SendRequestRequestRequired(aIssueCredentialV2SendRequestRequest)
	})
}
