/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2Store200Response struct {

	State *interface{} `json:"state"`

	ThreadId string `json:"thread_id"`

	CredentialId string `json:"credential_id,omitempty"`

	Indy IssueCredentialV2Store200ResponseAllOfIndy `json:"indy"`

	JsonLd IssueCredentialV2Store200ResponseAllOfIndy `json:"json-ld"`
}

// AssertIssueCredentialV2Store200ResponseRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2Store200ResponseRequired(obj IssueCredentialV2Store200Response) error {
	elements := map[string]interface{}{
		"state": obj.State,
		"thread_id": obj.ThreadId,
		"indy": obj.Indy,
		"json-ld": obj.JsonLd,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialV2Store200ResponseAllOfIndyRequired(obj.Indy); err != nil {
		return err
	}
	if err := AssertIssueCredentialV2Store200ResponseAllOfIndyRequired(obj.JsonLd); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialV2Store200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2Store200Response (e.g. [][]IssueCredentialV2Store200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2Store200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2Store200Response, ok := obj.(IssueCredentialV2Store200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2Store200ResponseRequired(aIssueCredentialV2Store200Response)
	})
}
