/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofV3SendProposalRequest struct {

	Data SendProposalData `json:"data"`
}

// AssertPresentProofV3SendProposalRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofV3SendProposalRequestRequired(obj PresentProofV3SendProposalRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendProposalDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecursePresentProofV3SendProposalRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofV3SendProposalRequest (e.g. [][]PresentProofV3SendProposalRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofV3SendProposalRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofV3SendProposalRequest, ok := obj.(PresentProofV3SendProposalRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofV3SendProposalRequestRequired(aPresentProofV3SendProposalRequest)
	})
}
