/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateOfferToStartCredentialIssuanceFlowData struct {

	Comment string `json:"comment,omitempty"`

	CredentialPreview CredentialPreview `json:"credential_preview"`

	CredDefId string `json:"cred_def_id"`
}

// AssertCreateOfferToStartCredentialIssuanceFlowDataRequired checks if the required fields are not zero-ed
func AssertCreateOfferToStartCredentialIssuanceFlowDataRequired(obj CreateOfferToStartCredentialIssuanceFlowData) error {
	elements := map[string]interface{}{
		"credential_preview": obj.CredentialPreview,
		"cred_def_id": obj.CredDefId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCredentialPreviewRequired(obj.CredentialPreview); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateOfferToStartCredentialIssuanceFlowDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateOfferToStartCredentialIssuanceFlowData (e.g. [][]CreateOfferToStartCredentialIssuanceFlowData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateOfferToStartCredentialIssuanceFlowDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateOfferToStartCredentialIssuanceFlowData, ok := obj.(CreateOfferToStartCredentialIssuanceFlowData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateOfferToStartCredentialIssuanceFlowDataRequired(aCreateOfferToStartCredentialIssuanceFlowData)
	})
}
