/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DidExchangeReceiveRequestResolvableDidRequest struct {

	Data map[string]interface{} `json:"data"`
}

// AssertDidExchangeReceiveRequestResolvableDidRequestRequired checks if the required fields are not zero-ed
func AssertDidExchangeReceiveRequestResolvableDidRequestRequired(obj DidExchangeReceiveRequestResolvableDidRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDidExchangeReceiveRequestResolvableDidRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DidExchangeReceiveRequestResolvableDidRequest (e.g. [][]DidExchangeReceiveRequestResolvableDidRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDidExchangeReceiveRequestResolvableDidRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDidExchangeReceiveRequestResolvableDidRequest, ok := obj.(DidExchangeReceiveRequestResolvableDidRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDidExchangeReceiveRequestResolvableDidRequestRequired(aDidExchangeReceiveRequestResolvableDidRequest)
	})
}
