/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV3SendProposalRequestData struct {

	ConnectionId string `json:"connection_id"`

	Pthid string `json:"pthid"`
}

// AssertIssueCredentialV3SendProposalRequestDataRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV3SendProposalRequestDataRequired(obj IssueCredentialV3SendProposalRequestData) error {
	elements := map[string]interface{}{
		"connection_id": obj.ConnectionId,
		"pthid": obj.Pthid,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIssueCredentialV3SendProposalRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV3SendProposalRequestData (e.g. [][]IssueCredentialV3SendProposalRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV3SendProposalRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV3SendProposalRequestData, ok := obj.(IssueCredentialV3SendProposalRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV3SendProposalRequestDataRequired(aIssueCredentialV3SendProposalRequestData)
	})
}
