/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OutOfBandReceiveInvitationRequest struct {

	Data OutOfBandReceiveInvitationRequestData `json:"data"`
}

// AssertOutOfBandReceiveInvitationRequestRequired checks if the required fields are not zero-ed
func AssertOutOfBandReceiveInvitationRequestRequired(obj OutOfBandReceiveInvitationRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertOutOfBandReceiveInvitationRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseOutOfBandReceiveInvitationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OutOfBandReceiveInvitationRequest (e.g. [][]OutOfBandReceiveInvitationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOutOfBandReceiveInvitationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOutOfBandReceiveInvitationRequest, ok := obj.(OutOfBandReceiveInvitationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOutOfBandReceiveInvitationRequestRequired(aOutOfBandReceiveInvitationRequest)
	})
}
