/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IssueCredentialState : All possible issue credential state values
type IssueCredentialState string

// List of IssueCredentialState
const (
	PROPOSAL_SENT IssueCredentialState = "proposal-sent"
	PROPOSAL_RECEIVED IssueCredentialState = "proposal-received"
	OFFER_SENT IssueCredentialState = "offer-sent"
	OFFER_RECEIVED IssueCredentialState = "offer-received"
	REQUEST_SENT IssueCredentialState = "request-sent"
	REQUEST_RECEIVED IssueCredentialState = "request-received"
	CREDENTIAL_ISSUED IssueCredentialState = "credential-issued"
	CREDENTIAL_RECEIVED IssueCredentialState = "credential-received"
	DONE IssueCredentialState = "done"
)
