/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionReceiveInvitation200Response struct {

	ConnectionId string `json:"connection_id,omitempty"`

	State ConnectionState `json:"state,omitempty"`
}

// AssertConnectionReceiveInvitation200ResponseRequired checks if the required fields are not zero-ed
func AssertConnectionReceiveInvitation200ResponseRequired(obj ConnectionReceiveInvitation200Response) error {
	return nil
}

// AssertRecurseConnectionReceiveInvitation200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionReceiveInvitation200Response (e.g. [][]ConnectionReceiveInvitation200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionReceiveInvitation200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionReceiveInvitation200Response, ok := obj.(ConnectionReceiveInvitation200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionReceiveInvitation200ResponseRequired(aConnectionReceiveInvitation200Response)
	})
}
