/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofV3SendRequestRequestDataPresentationRequest struct {

	Format string `json:"format"`

	Comment string `json:"comment,omitempty"`

	Data map[string]interface{} `json:"data"`
}

// AssertPresentProofV3SendRequestRequestDataPresentationRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofV3SendRequestRequestDataPresentationRequestRequired(obj PresentProofV3SendRequestRequestDataPresentationRequest) error {
	elements := map[string]interface{}{
		"format": obj.Format,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentProofV3SendRequestRequestDataPresentationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofV3SendRequestRequestDataPresentationRequest (e.g. [][]PresentProofV3SendRequestRequestDataPresentationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofV3SendRequestRequestDataPresentationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofV3SendRequestRequestDataPresentationRequest, ok := obj.(PresentProofV3SendRequestRequestDataPresentationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofV3SendRequestRequestDataPresentationRequestRequired(aPresentProofV3SendRequestRequestDataPresentationRequest)
	})
}
