/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialCreateOffer200ResponseRecordAllOf struct {

	State *interface{} `json:"state,omitempty"`
}

// AssertIssueCredentialCreateOffer200ResponseRecordAllOfRequired checks if the required fields are not zero-ed
func AssertIssueCredentialCreateOffer200ResponseRecordAllOfRequired(obj IssueCredentialCreateOffer200ResponseRecordAllOf) error {
	return nil
}

// AssertRecurseIssueCredentialCreateOffer200ResponseRecordAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialCreateOffer200ResponseRecordAllOf (e.g. [][]IssueCredentialCreateOffer200ResponseRecordAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialCreateOffer200ResponseRecordAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialCreateOffer200ResponseRecordAllOf, ok := obj.(IssueCredentialCreateOffer200ResponseRecordAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialCreateOffer200ResponseRecordAllOfRequired(aIssueCredentialCreateOffer200ResponseRecordAllOf)
	})
}
