/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SchemaCreateRequest struct {

	Data SchemaCreateRequestData `json:"data"`
}

// AssertSchemaCreateRequestRequired checks if the required fields are not zero-ed
func AssertSchemaCreateRequestRequired(obj SchemaCreateRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSchemaCreateRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSchemaCreateRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SchemaCreateRequest (e.g. [][]SchemaCreateRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSchemaCreateRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSchemaCreateRequest, ok := obj.(SchemaCreateRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSchemaCreateRequestRequired(aSchemaCreateRequest)
	})
}
