/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RevocationRevokeCredentialRequest struct {

	Data RevocationRevokeCredentialRequestData `json:"data"`
}

// AssertRevocationRevokeCredentialRequestRequired checks if the required fields are not zero-ed
func AssertRevocationRevokeCredentialRequestRequired(obj RevocationRevokeCredentialRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertRevocationRevokeCredentialRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseRevocationRevokeCredentialRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RevocationRevokeCredentialRequest (e.g. [][]RevocationRevokeCredentialRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRevocationRevokeCredentialRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRevocationRevokeCredentialRequest, ok := obj.(RevocationRevokeCredentialRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRevocationRevokeCredentialRequestRequired(aRevocationRevokeCredentialRequest)
	})
}
