/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialCreateOfferRequest struct {

	Data CreateOfferToStartCredentialIssuanceFlowData `json:"data"`
}

// AssertIssueCredentialCreateOfferRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialCreateOfferRequestRequired(obj IssueCredentialCreateOfferRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateOfferToStartCredentialIssuanceFlowDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialCreateOfferRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialCreateOfferRequest (e.g. [][]IssueCredentialCreateOfferRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialCreateOfferRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialCreateOfferRequest, ok := obj.(IssueCredentialCreateOfferRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialCreateOfferRequestRequired(aIssueCredentialCreateOfferRequest)
	})
}
