/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DidCommV2AcceptInvitationRequest struct {

	Data DidCommV2AcceptInvitationRequestData `json:"data"`
}

// AssertDidCommV2AcceptInvitationRequestRequired checks if the required fields are not zero-ed
func AssertDidCommV2AcceptInvitationRequestRequired(obj DidCommV2AcceptInvitationRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertDidCommV2AcceptInvitationRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseDidCommV2AcceptInvitationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DidCommV2AcceptInvitationRequest (e.g. [][]DidCommV2AcceptInvitationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDidCommV2AcceptInvitationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDidCommV2AcceptInvitationRequest, ok := obj.(DidCommV2AcceptInvitationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDidCommV2AcceptInvitationRequestRequired(aDidCommV2AcceptInvitationRequest)
	})
}
