/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialStore200ResponseAllOf struct {

	State *interface{} `json:"state,omitempty"`
}

// AssertIssueCredentialStore200ResponseAllOfRequired checks if the required fields are not zero-ed
func AssertIssueCredentialStore200ResponseAllOfRequired(obj IssueCredentialStore200ResponseAllOf) error {
	return nil
}

// AssertRecurseIssueCredentialStore200ResponseAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialStore200ResponseAllOf (e.g. [][]IssueCredentialStore200ResponseAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialStore200ResponseAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialStore200ResponseAllOf, ok := obj.(IssueCredentialStore200ResponseAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialStore200ResponseAllOfRequired(aIssueCredentialStore200ResponseAllOf)
	})
}
