/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionSendPingRequestData struct {

	Comment string `json:"comment"`
}

// AssertConnectionSendPingRequestDataRequired checks if the required fields are not zero-ed
func AssertConnectionSendPingRequestDataRequired(obj ConnectionSendPingRequestData) error {
	elements := map[string]interface{}{
		"comment": obj.Comment,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseConnectionSendPingRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionSendPingRequestData (e.g. [][]ConnectionSendPingRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionSendPingRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionSendPingRequestData, ok := obj.(ConnectionSendPingRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionSendPingRequestDataRequired(aConnectionSendPingRequestData)
	})
}
