/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofV2SendPresentationRequest struct {

	Id string `json:"id"`

	Data map[string]interface{} `json:"data"`
}

// AssertPresentProofV2SendPresentationRequestRequired checks if the required fields are not zero-ed
func AssertPresentProofV2SendPresentationRequestRequired(obj PresentProofV2SendPresentationRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentProofV2SendPresentationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofV2SendPresentationRequest (e.g. [][]PresentProofV2SendPresentationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofV2SendPresentationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofV2SendPresentationRequest, ok := obj.(PresentProofV2SendPresentationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofV2SendPresentationRequestRequired(aPresentProofV2SendPresentationRequest)
	})
}
