/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendProposalData struct {

	PresentationProposal SendProposalDataPresentationProposal `json:"presentation_proposal"`
}

// AssertSendProposalDataRequired checks if the required fields are not zero-ed
func AssertSendProposalDataRequired(obj SendProposalData) error {
	elements := map[string]interface{}{
		"presentation_proposal": obj.PresentationProposal,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSendProposalDataPresentationProposalRequired(obj.PresentationProposal); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSendProposalDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendProposalData (e.g. [][]SendProposalData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendProposalDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendProposalData, ok := obj.(SendProposalData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendProposalDataRequired(aSendProposalData)
	})
}
