/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SendRequestToStartCredentialIssuanceFlow struct {

	Id string `json:"id"`
}

// AssertSendRequestToStartCredentialIssuanceFlowRequired checks if the required fields are not zero-ed
func AssertSendRequestToStartCredentialIssuanceFlowRequired(obj SendRequestToStartCredentialIssuanceFlow) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSendRequestToStartCredentialIssuanceFlowRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SendRequestToStartCredentialIssuanceFlow (e.g. [][]SendRequestToStartCredentialIssuanceFlow), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSendRequestToStartCredentialIssuanceFlowRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSendRequestToStartCredentialIssuanceFlow, ok := obj.(SendRequestToStartCredentialIssuanceFlow)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSendRequestToStartCredentialIssuanceFlowRequired(aSendRequestToStartCredentialIssuanceFlow)
	})
}
