/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateOfferToStartCredentialIssuanceFlow struct {

	Data CreateOfferToStartCredentialIssuanceFlowData `json:"data"`
}

// AssertCreateOfferToStartCredentialIssuanceFlowRequired checks if the required fields are not zero-ed
func AssertCreateOfferToStartCredentialIssuanceFlowRequired(obj CreateOfferToStartCredentialIssuanceFlow) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateOfferToStartCredentialIssuanceFlowDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseCreateOfferToStartCredentialIssuanceFlowRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateOfferToStartCredentialIssuanceFlow (e.g. [][]CreateOfferToStartCredentialIssuanceFlow), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateOfferToStartCredentialIssuanceFlowRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateOfferToStartCredentialIssuanceFlow, ok := obj.(CreateOfferToStartCredentialIssuanceFlow)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateOfferToStartCredentialIssuanceFlowRequired(aCreateOfferToStartCredentialIssuanceFlow)
	})
}
