/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConnectionReceiveInvitationRequestData struct {
	Type                 string   `json:"@type,omitempty"`
	InvitationId         string   `json:"@id,omitempty"`
	ServiceEndpoint      string   `json:"serviceEndpoint,omitempty"`
	RecipientKeys        []string `json:"recipientKeys,omitempty"`
	RoutingKeys          []string `json:"routingKeys,omitempty"`
	Label                string   `json:"label,omitempty"`
	MediatorConnectionId string   `json:"mediator_connection_id,omitempty"`
}

// AssertConnectionReceiveInvitationRequestDataRequired checks if the required fields are not zero-ed
func AssertConnectionReceiveInvitationRequestDataRequired(obj ConnectionReceiveInvitationRequestData) error {
	return nil
}

// AssertRecurseConnectionReceiveInvitationRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConnectionReceiveInvitationRequestData (e.g. [][]ConnectionReceiveInvitationRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConnectionReceiveInvitationRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConnectionReceiveInvitationRequestData, ok := obj.(ConnectionReceiveInvitationRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConnectionReceiveInvitationRequestDataRequired(aConnectionReceiveInvitationRequestData)
	})
}
