/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialIssueRequestData struct {

	Comment string `json:"comment,omitempty"`
}

// AssertIssueCredentialIssueRequestDataRequired checks if the required fields are not zero-ed
func AssertIssueCredentialIssueRequestDataRequired(obj IssueCredentialIssueRequestData) error {
	return nil
}

// AssertRecurseIssueCredentialIssueRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialIssueRequestData (e.g. [][]IssueCredentialIssueRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialIssueRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialIssueRequestData, ok := obj.(IssueCredentialIssueRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialIssueRequestDataRequired(aIssueCredentialIssueRequestData)
	})
}
