/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofSendPresentationRequestData struct {
	RequestedAttributes    map[string]interface{} `json:"requested_attributes,omitempty"`
	RequestedPredicates    map[string]interface{} `json:"requested_predicates,omitempty"`
	SelfAttestedAttributes map[string]interface{} `json:"self_attested_attributes,omitempty"`
	Comment                string                 `json:"comment,omitempty"`
}

// AssertPresentProofSendPresentationRequestDataRequired checks if the required fields are not zero-ed
func AssertPresentProofSendPresentationRequestDataRequired(obj PresentProofSendPresentationRequestData) error {
	return nil
}

// AssertRecursePresentProofSendPresentationRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofSendPresentationRequestData (e.g. [][]PresentProofSendPresentationRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofSendPresentationRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofSendPresentationRequestData, ok := obj.(PresentProofSendPresentationRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofSendPresentationRequestDataRequired(aPresentProofSendPresentationRequestData)
	})
}
