/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV2SendProposalRequest struct {

	Data IssueCredentialV2SendProposalRequestData `json:"data"`
}

// AssertIssueCredentialV2SendProposalRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV2SendProposalRequestRequired(obj IssueCredentialV2SendProposalRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialV2SendProposalRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialV2SendProposalRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV2SendProposalRequest (e.g. [][]IssueCredentialV2SendProposalRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV2SendProposalRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV2SendProposalRequest, ok := obj.(IssueCredentialV2SendProposalRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV2SendProposalRequestRequired(aIssueCredentialV2SendProposalRequest)
	})
}
