/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AttachmentFormat string

// List of AttachmentFormat
const (
	INDY AttachmentFormat = "indy"
	JSON_LD AttachmentFormat = "json-ld"
)

// AssertAttachmentFormatRequired checks if the required fields are not zero-ed
func AssertAttachmentFormatRequired(obj AttachmentFormat) error {
	return nil
}

// AssertRecurseAttachmentFormatRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AttachmentFormat (e.g. [][]AttachmentFormat), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAttachmentFormatRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAttachmentFormat, ok := obj.(AttachmentFormat)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAttachmentFormatRequired(aAttachmentFormat)
	})
}
