/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialV3SendProposalRequest struct {

	Data IssueCredentialV3SendProposalRequestData `json:"data"`
}

// AssertIssueCredentialV3SendProposalRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialV3SendProposalRequestRequired(obj IssueCredentialV3SendProposalRequest) error {
	elements := map[string]interface{}{
		"data": obj.Data,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialV3SendProposalRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialV3SendProposalRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialV3SendProposalRequest (e.g. [][]IssueCredentialV3SendProposalRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialV3SendProposalRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialV3SendProposalRequest, ok := obj.(IssueCredentialV3SendProposalRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialV3SendProposalRequestRequired(aIssueCredentialV3SendProposalRequest)
	})
}
