/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentationPreviewAttributesInner struct {

	Name string `json:"name"`

	CredDefId string `json:"cred_def_id,omitempty"`

	MimeType string `json:"mime-type,omitempty"`

	Value string `json:"value,omitempty"`

	Referent string `json:"referent,omitempty"`
}

// AssertPresentationPreviewAttributesInnerRequired checks if the required fields are not zero-ed
func AssertPresentationPreviewAttributesInnerRequired(obj PresentationPreviewAttributesInner) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentationPreviewAttributesInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentationPreviewAttributesInner (e.g. [][]PresentationPreviewAttributesInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentationPreviewAttributesInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentationPreviewAttributesInner, ok := obj.(PresentationPreviewAttributesInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentationPreviewAttributesInnerRequired(aPresentationPreviewAttributesInner)
	})
}
