/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialStore200Response struct {

	//State *interface{} `json:"state"`
	State IssueCredentialState `json:"state"`

	ThreadId string `json:"thread_id"`

	CredentialId string `json:"credential_id"`
}

// AssertIssueCredentialStore200ResponseRequired checks if the required fields are not zero-ed
func AssertIssueCredentialStore200ResponseRequired(obj IssueCredentialStore200Response) error {
	elements := map[string]interface{}{
		"state":         obj.State,
		"thread_id":     obj.ThreadId,
		"credential_id": obj.CredentialId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIssueCredentialStore200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialStore200Response (e.g. [][]IssueCredentialStore200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialStore200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialStore200Response, ok := obj.(IssueCredentialStore200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialStore200ResponseRequired(aIssueCredentialStore200Response)
	})
}
