/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialIssue200ResponseAllOf struct {

	State *interface{} `json:"state,omitempty"`
}

// AssertIssueCredentialIssue200ResponseAllOfRequired checks if the required fields are not zero-ed
func AssertIssueCredentialIssue200ResponseAllOfRequired(obj IssueCredentialIssue200ResponseAllOf) error {
	return nil
}

// AssertRecurseIssueCredentialIssue200ResponseAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialIssue200ResponseAllOf (e.g. [][]IssueCredentialIssue200ResponseAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialIssue200ResponseAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialIssue200ResponseAllOf, ok := obj.(IssueCredentialIssue200ResponseAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialIssue200ResponseAllOfRequired(aIssueCredentialIssue200ResponseAllOf)
	})
}
