/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RevocationGetNotificationByThreadId200Response struct {

	ThreadId string `json:"thread_id,omitempty"`
}

// AssertRevocationGetNotificationByThreadId200ResponseRequired checks if the required fields are not zero-ed
func AssertRevocationGetNotificationByThreadId200ResponseRequired(obj RevocationGetNotificationByThreadId200Response) error {
	return nil
}

// AssertRecurseRevocationGetNotificationByThreadId200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RevocationGetNotificationByThreadId200Response (e.g. [][]RevocationGetNotificationByThreadId200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRevocationGetNotificationByThreadId200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRevocationGetNotificationByThreadId200Response, ok := obj.(RevocationGetNotificationByThreadId200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRevocationGetNotificationByThreadId200ResponseRequired(aRevocationGetNotificationByThreadId200Response)
	})
}
