/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialSendRequest200Response struct {

	State *interface{} `json:"state"`

	ThreadId string `json:"thread_id"`

	CredentialId string `json:"credential_id,omitempty"`
}

// AssertIssueCredentialSendRequest200ResponseRequired checks if the required fields are not zero-ed
func AssertIssueCredentialSendRequest200ResponseRequired(obj IssueCredentialSendRequest200Response) error {
	elements := map[string]interface{}{
		"state": obj.State,
		"thread_id": obj.ThreadId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseIssueCredentialSendRequest200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialSendRequest200Response (e.g. [][]IssueCredentialSendRequest200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialSendRequest200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialSendRequest200Response, ok := obj.(IssueCredentialSendRequest200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialSendRequest200ResponseRequired(aIssueCredentialSendRequest200Response)
	})
}
