/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type IssueCredentialIssueRequest struct {

	Id string `json:"id"`

	Data IssueCredentialIssueRequestData `json:"data,omitempty"`
}

// AssertIssueCredentialIssueRequestRequired checks if the required fields are not zero-ed
func AssertIssueCredentialIssueRequestRequired(obj IssueCredentialIssueRequest) error {
	elements := map[string]interface{}{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertIssueCredentialIssueRequestDataRequired(obj.Data); err != nil {
		return err
	}
	return nil
}

// AssertRecurseIssueCredentialIssueRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of IssueCredentialIssueRequest (e.g. [][]IssueCredentialIssueRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIssueCredentialIssueRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIssueCredentialIssueRequest, ok := obj.(IssueCredentialIssueRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIssueCredentialIssueRequestRequired(aIssueCredentialIssueRequest)
	})
}
