/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PresentProofSendProposal200Response struct {

	State *interface{} `json:"state"`

	ThreadId string `json:"thread_id"`
}

// AssertPresentProofSendProposal200ResponseRequired checks if the required fields are not zero-ed
func AssertPresentProofSendProposal200ResponseRequired(obj PresentProofSendProposal200Response) error {
	elements := map[string]interface{}{
		"state": obj.State,
		"thread_id": obj.ThreadId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePresentProofSendProposal200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PresentProofSendProposal200Response (e.g. [][]PresentProofSendProposal200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePresentProofSendProposal200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPresentProofSendProposal200Response, ok := obj.(PresentProofSendProposal200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPresentProofSendProposal200ResponseRequired(aPresentProofSendProposal200Response)
	})
}
