/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CredentialDefinitionCreate200Response struct {

	CredentialDefinitionId string `json:"credential_definition_id,omitempty"`
}

// AssertCredentialDefinitionCreate200ResponseRequired checks if the required fields are not zero-ed
func AssertCredentialDefinitionCreate200ResponseRequired(obj CredentialDefinitionCreate200Response) error {
	return nil
}

// AssertRecurseCredentialDefinitionCreate200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CredentialDefinitionCreate200Response (e.g. [][]CredentialDefinitionCreate200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCredentialDefinitionCreate200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCredentialDefinitionCreate200Response, ok := obj.(CredentialDefinitionCreate200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCredentialDefinitionCreate200ResponseRequired(aCredentialDefinitionCreate200Response)
	})
}
