/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AgentCommandIssueCredentialSendProposalData struct {

	Comment string `json:"comment,omitempty"`

	CredentialProposal CredentialPreview `json:"credential_proposal,omitempty"`

	SchemaIssuerDid string `json:"schema_issuer_did,omitempty"`

	SchemaId string `json:"schema_id,omitempty"`

	SchemaName string `json:"schema_name,omitempty"`

	SchemaVersion string `json:"schema_version,omitempty"`

	CredDefId string `json:"cred_def_id,omitempty"`

	IssuerDid string `json:"issuer_did,omitempty"`

	ConnectionId string `json:"connection_id"`
}
