/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DidCommV2AcceptInvitationRequestData struct {

	Invitation map[string]interface{} `json:"invitation,omitempty"`
}

// AssertDidCommV2AcceptInvitationRequestDataRequired checks if the required fields are not zero-ed
func AssertDidCommV2AcceptInvitationRequestDataRequired(obj DidCommV2AcceptInvitationRequestData) error {
	return nil
}

// AssertRecurseDidCommV2AcceptInvitationRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DidCommV2AcceptInvitationRequestData (e.g. [][]DidCommV2AcceptInvitationRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDidCommV2AcceptInvitationRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDidCommV2AcceptInvitationRequestData, ok := obj.(DidCommV2AcceptInvitationRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDidCommV2AcceptInvitationRequestDataRequired(aDidCommV2AcceptInvitationRequestData)
	})
}
