/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DidCommV2CreateInvitationRequestData struct {

	GoalCode string `json:"goal-code,omitempty"`
}

// AssertDidCommV2CreateInvitationRequestDataRequired checks if the required fields are not zero-ed
func AssertDidCommV2CreateInvitationRequestDataRequired(obj DidCommV2CreateInvitationRequestData) error {
	return nil
}

// AssertRecurseDidCommV2CreateInvitationRequestDataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DidCommV2CreateInvitationRequestData (e.g. [][]DidCommV2CreateInvitationRequestData), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDidCommV2CreateInvitationRequestDataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDidCommV2CreateInvitationRequestData, ok := obj.(DidCommV2CreateInvitationRequestData)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDidCommV2CreateInvitationRequestDataRequired(aDidCommV2CreateInvitationRequestData)
	})
}
