/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StatusGet200Response struct {

	Status string `json:"status,omitempty"`
}

// AssertStatusGet200ResponseRequired checks if the required fields are not zero-ed
func AssertStatusGet200ResponseRequired(obj StatusGet200Response) error {
	return nil
}

// AssertRecurseStatusGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StatusGet200Response (e.g. [][]StatusGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStatusGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStatusGet200Response, ok := obj.(StatusGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStatusGet200ResponseRequired(aStatusGet200Response)
	})
}
