/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// SchemaApiService is a service that implents the logic for the SchemaApiServicer
// This service should implement the business logic for every endpoint for the SchemaApi API. 
// Include any external packages or services that will be required by this service.
type SchemaApiService struct {
}

// NewSchemaApiService creates a default api service
func NewSchemaApiService() SchemaApiServicer {
	return &SchemaApiService{}
}

// SchemaCreate - Create a new schema
func (s *SchemaApiService) SchemaCreate(ctx context.Context, inlineObject4 InlineObject4) (ImplResponse, error) {
	// TODO - update SchemaCreate with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse2004{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse2004{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SchemaCreate method not implemented")
}

// SchemaGetById - Get schema by id
func (s *SchemaApiService) SchemaGetById(ctx context.Context, schemaId string) (ImplResponse, error) {
	// TODO - update SchemaGetById with the required logic for this service method.
	// Add api_schema_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("SchemaGetById method not implemented")
}

