/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"

	"github.com/findy-network/findy-agent-backchannel/agent"
)

// PresentProofApiService is a service that implents the logic for the PresentProofApiServicer
// This service should implement the business logic for every endpoint for the PresentProofApi API.
// Include any external packages or services that will be required by this service.
type PresentProofApiService struct {
	a *agent.Agent
}

// NewPresentProofApiService creates a default api service
func NewPresentProofApiService(a *agent.Agent) PresentProofApiServicer {
	return &PresentProofApiService{
		a: a,
	}
}

// PresentProofGetByThreadId - Get presentation exchange record by thread id
func (s *PresentProofApiService) PresentProofGetByThreadId(ctx context.Context, presentationExchangeThreadId string) (ImplResponse, error) {
	if cred, err := s.a.GetProof(presentationExchangeThreadId); err == nil {
		return Response(200, PresentProofOperationResponse{
			State:    PROOF_DONE,
			ThreadId: cred.ID,
		}), nil

	}
	if threadID, _ := s.a.GetSentProof(presentationExchangeThreadId); threadID != "" {
		return Response(200, PresentProofOperationResponse{
			State:    PROOF_PRESENTATION_SENT,
			ThreadId: threadID,
		}), nil
	}
	if threadID, _ := s.a.GetProofRequest(presentationExchangeThreadId); threadID != "" {
		return Response(200, PresentProofOperationResponse{
			State:    PROOF_REQUEST_RECEIVED,
			ThreadId: threadID,
		}), nil
	}
	return Response(http.StatusNotFound, nil), nil
}

// PresentProofSendPresentation - Send presentation
func (s *PresentProofApiService) PresentProofSendPresentation(ctx context.Context, inlineObject9 InlineObject9) (ImplResponse, error) {
	threadId, err := s.a.SendProofPresentation(inlineObject9.Id)
	if err == nil {
		return Response(200, PresentProofOperationResponse{State: PROOF_PRESENTATION_SENT, ThreadId: threadId}), nil
	}

	return Response(http.StatusInternalServerError, nil), err
}

// PresentProofSendProposal - Send presentation proposal
func (s *PresentProofApiService) PresentProofSendProposal(ctx context.Context, inlineObject7 InlineObject7) (ImplResponse, error) {
	connectionID := inlineObject7.Data.ConnectionId
	proposalAttributes := inlineObject7.Data.PresentationProposal.Attributes
	attributes := make([]*agent.ProofAttribute, 0)
	for _, attr := range proposalAttributes {
		attributes = append(attributes, &agent.ProofAttribute{
			Name:      attr.Name,
			CredDefID: attr.CredDefId,
		})
	}

	threadId, err := s.a.ProposeProof(connectionID, attributes)
	if err == nil {
		return Response(200, PresentProofOperationResponse{State: PROOF_PROPOSAL_SENT, ThreadId: threadId}), nil
	}

	return Response(http.StatusInternalServerError, nil), err
}

// PresentProofSendRequest - Send presentation request
func (s *PresentProofApiService) PresentProofSendRequest(ctx context.Context, inlineObject8 InlineObject8) (ImplResponse, error) {
	// TODO - update PresentProofSendRequest with the required logic for this service method.
	// Add api_present_proof_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, PresentProofOperationResponse{}) or use other options such as http.Ok ...
	//return Response(200, PresentProofOperationResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PresentProofSendRequest method not implemented")
}

// PresentProofVerifyPresentation - Verify presentation
func (s *PresentProofApiService) PresentProofVerifyPresentation(ctx context.Context, inlineObject10 InlineObject10) (ImplResponse, error) {
	// TODO - update PresentProofVerifyPresentation with the required logic for this service method.
	// Add api_present_proof_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, PresentProofOperationResponse{}) or use other options such as http.Ok ...
	//return Response(200, PresentProofOperationResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PresentProofVerifyPresentation method not implemented")
}
