/*
 * Aries Agent Test Harness Backchannel API
 *
 * This page documents the backchannel API the test harness uses to communicate with agents under tests.  For more information checkout the [Aries Interoperability Information](http://aries-interop.info) page. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ConnectionState : All possible connection state values
type ConnectionState string

// List of ConnectionState
const (
	INVITATION ConnectionState = "invitation"
	REQUEST ConnectionState = "request"
	RESPONSE ConnectionState = "response"
	ACTIVE ConnectionState = "active"
)
